# Generated by Django 2.1.5 on 2019-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_favcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favcolor',
            field=models.TextField(null=True),
        ),
    ]
